### ISSUE TITLE
CSRF token validation failed

### ISSUE THREAD

**Issue by fotuzlab** [droath/restful_user_registration#1]
Hi Droath,

Thanks for the module. I was trying to use it but facing an issue.

I am using postman to make a call(SS attached). Sending over name, pass and mail and CSRF token received through http://api.clinicfinder.lab/api/session/token

I am sure it is some small thing that I am missing but unable to spot it. Can you please help?

![csrf-token-required](https://cloud.githubusercontent.com/assets/1704884/10932989/39c35cc8-82fb-11e5-8c00-d7e169e9baa5.png)

**Comment by droath** [comment]
@fotuzlab 

You'll need to send the request data as a JSON object within the request body. Your endpoint will look like this `http://api.clinicfinder.lab/api/v1.0/user_registration`. The JSON body format is: 

``` json
{
    "name": "arijit",
    "pass": "arijit",
    "mail": "er.arijitdutta@gmail.com", 
    "roles": [],
}
```

If your adding a new user use the `POST` method, if you're updating then use `PUT`. That should work as long as you're authenticated. I've tested it to work with Basic Auth, which you can configure within postman under the authentication section. Credentials are the same as the ones you use to login for your Drupal application.
